using System.ComponentModel.DataAnnotations.Schema;

namespace MallManagmentSystem.Models
{
    /// <summary>
    /// Represents the financial statistics and metrics for the mall management system.
    /// This model aggregates various financial data points to provide a comprehensive view of the mall's financial performance.
    /// </summary>
    public class FinancialStatistics
    {
        /// <summary>
        /// Gets or sets the total revenue generated by the mall from all sources.
        /// This includes rent income, service charges, and other revenue streams.
        /// </summary>
        [Column(TypeName = "decimal(18,2)")]
        public decimal TotalRevenue { get; set; }

        /// <summary>
        /// Gets or sets the total expenses incurred by the mall.
        /// This includes operational costs, maintenance, utilities, and other expenses.
        /// </summary>
        [Column(TypeName = "decimal(18,2)")]
        public decimal TotalExpenses { get; set; }

        /// <summary>
        /// Gets or sets the total income generated from store rentals.
        /// This represents the sum of all rent payments received from store tenants.
        /// </summary>
        [Column(TypeName = "decimal(18,2)")]
        public decimal TotalRentIncome { get; set; }

        /// <summary>
        /// Gets or sets the total amount of loans taken by the mall.
        /// This represents the sum of all outstanding loans and financial obligations.
        /// </summary>
        [Column(TypeName = "decimal(18,2)")]
        public decimal TotalLoans { get; set; }

        /// <summary>
        /// Gets or sets the total amount of debits or outstanding payments.
        /// This includes unpaid bills, pending payments, and other financial obligations.
        /// </summary>
        [Column(TypeName = "decimal(18,2)")]
        public decimal TotalDebits { get; set; }

        /// <summary>
        /// Gets or sets the net profit of the mall.
        /// This is calculated as TotalRevenue minus TotalExpenses.
        /// </summary>
        [Column(TypeName = "decimal(18,2)")]
        public decimal NetProfit { get; set; }
        public decimal TotalRentCollected { get; internal set; }
        public decimal TotalRentDue { get; internal set; }
        public decimal TotalRentOverdue { get; internal set; }
    }
} 